# Generated by Django 4.2.7 on 2023-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_image_remove_user_is_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
