# Generated by Django 4.2.7 on 2023-11-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
