# Generated by Django 4.2.7 on 2023-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='member code'),
        ),
    ]
